### ISSUE TITLE
DOSOPT-2주차 세미나

### ISSUE THREAD

**Issue by mcrkgus** [DO-SOPT-iOS-Part/KimGaHyun-assignment#1]
## 🛠 Issue
- 시작 화면에서 나의 위치 뷰를 선택하면, 2번째 화면의 날씨 상세보기 뷰로 Push 되어 이동
- 시작 화면 수직 스크롤뷰
- 날씨 상세보기 화면 수직 스크롤뷰
- 시간대 날씨 수평 스크롤뷰
- 하단의 리스트 보기 버튼 선태하면, 시작 화면으로 POP

## 📋 To-do
- [x] #2
- [x] 화면에서 사용되는 이미지 다운로드 후 asset에 추가
- [x] 시작 화면 레이아웃 잡기
- [x] 2번째 화면 레이아웃 잡기
- [x] 시작 화면 수직 스크롤뷰
- [x] 날씨 상세보기 화면 수직 스크롤뷰
- [x] 시간대 날씨 수평 스크롤뷰
- [x] 시작 화면에서 위치 뷰 선택하면 다음 화면으로 Push
- [x] 상세보기 화면에서 하단 리스트 선택하면 시작 화면으로 POP
