### ISSUE TITLE
[Feat] 3주차 세미나 과제

### ISSUE THREAD

**Issue by mcrkgus** [DO-SOPT-iOS-Part/KimGaHyun-assignment#4]
## 🗣️Description
- 3차 세미나 과제 
  
## ⚙️TODO
- [] 날씨 리스트 TableView로 변경
- [] 날씨 세부 리스트 CollectionView로 변경
- [] 날씨 세부 리스트에 요일 별 날씨 정보 추가
